### ISSUE TITLE
Blog!

### ISSUE THREAD

**Issue by Xaviju** [una/ama#11]
I see that you keep your blog updated and it is actually very interesting. I tried to do it several times (more as a personal notes blog) but I ended up editing it and trying _the new thing_ instead of actually writing.

Any advice on how to avoid the blank post syndrome?

Congrats!

**Comment by una** [comment]
Maybe try to write a blog post _before_ building a blog website (you know.. content is king and all :smile: ) I like using a static site generator because it allows me to just write in markdown and no worry about it. Another good thing to do is to set a deadline, i.e. "This week I will spend X hours writing a post on ___ and will publish by ____." If you can't hold yourself accountable, send the blog to a friend to edit (let them know your deadline for sending it over for edits). Lastly, keep a running list of blog post ideas to refer to whenever you have time to write but don't know what to write about. 

I usually get the best blog ideas in the strangest of places...

Good luck!
