### ISSUE TITLE
How did you decide to work in the IT department, even when the world said otherwise?

### ISSUE THREAD

**Issue by diessica** [una/ama#20]
I've never introduced to computers by my environment. 

In my childhood, girls had no interest in computers. In high school, I was the only girl who was into computer stuff. When working at companies, I always worked among men.

I like to think that my curiosity brought me here, **even when the world said otherwise**.

But I want to hear from you, Una! What is your story?

**Comment by una** [comment]
Okay I've been thinking about the "why" a lot lately, and have been wanting to sit down and write it out, so uhh... here's the story.

When I think back, I was introduced to computers early on. My parents had a very laissez-faire approach to computers and I was on AOL Instant Messenger chat rooms since I was 6 years old (seriously. I would report people for cursing because it was against the rules, and nobody believed my age when I honestly answered A/S/L). I remember I was 6 because my username had a 6 in it for my age.

I don't know _why_ they were so lenient, but I'm convinced its part of the reason I am where I am today. My parents are **very** traditional Ukrainian immigrants but I always showed an interest in technology, even more-so than my brother, so my Dad would tell me bed-time stories (AKA would teach me about how a CPU worked and about the history of keyboards). He loved talking about it, while my mother rolled her eyes. My Dad is an electrical engineer and the computer that we had in our household was built by him salvaging broken computer parts and fixing them up, so he knew how it worked. I was absolutely fascinated by the long “highway-like” flat, white, "bundles" of wires — I still remember it well when he opened up the computer and called me over to explain its internals.

Anyway, I also started "designing" at a very young age -- making pixel-by-pixel cartoon dolls on this chat program called [The Palace](https://en.wikipedia.org/wiki/The_Palace_%28computer_program%29). There was a huge cartoon doll community and I made a Geocities site for my cartoon dolls (and really bad poetry). When Neopets came out, I learned HTML from their [Pet Pages](http://www.neopets.com/help/html1.phtml) and then by the time Myspace was a thing, I was building layouts for all of my friends. In 3rd grade, I had a fake magazine called "U.N.A Magazine" that had monthly issues in which I drew (and priced!) clothing. Recently I found it in my childhood bedroom and there was an article I wrote in it (on lined paper in pencil) about making your own web page. So y'all, I was writing technical articles since 8 years old :information_desk_person: 

In high school, I took a "multimedia design" class when I learned ActionScript 2.0 :smile: and instead of drawing static cartoon dolls, I was building drag-and-drop flash games (I was also introduced to the Wacom tablet at this time and was mind blown). I made about 3 flash portfolios, several animations, and a few games by the time I graduated. So I've kind of always been doing "digital design" throughout middle and high school.

I went into university double-majoring in both graphic design and computer science. In my first web design class, we learned Dreamweaver, but my professor didn't really know how to use Dreamweaver (i.e. all of the form elements and pre-made items that make it so convenient) so we just used it as a text editor. Which was **awesome**. I really excelled in this class because of my Myspace days and natural curiosity. I remember CSS3 was really new and so were "responsive" websites. But as soon as I learned about the concept, I never made a "non-responsive" website again, even though we didn't really go over it at my grade-level. My professor used my website as an example for the seniors. And that was really empowering because they were 3 years older than me and it taught me that I could build anything and set my own expectations for myself. (Did I mention I was a huge nerd in College?)

When I took Computer Science classes, they were hard for me. Really hard. I remember there was one class that started with only 7 girls in it and by the second week, 3 girls including me and [Ally Palanzi](http://twitter.com/mylifeasalllly), who later became my best friend/roomate/Front-End Engineer at Vox Media, stayed in the class. I had an _excellent_ Python professor and went to _every_ office hours session he held. When I say _every_, I really mean **every**. The CS program I was in was very small. We all got really close. There were nights where I was building Java apps at 3 AM, struggling, and wondering why the hell I was doing this to myself. One night I was working on a program with Ally, getting nowhere, and said out loud "I can't do this. I'm just going to fail computer science" Nathaniel, the president of the CS club at the time, was also there, looked up at us and said — _“don’t worry, you're not going to fail. We’re not going to let you fail.”_ That encouragement meant a lot. The community meant a lot. I got an "A" in the class.

I was honestly surrounded by the most genuine group of individuals who were interested in helping each other learn instead of competing against each other. I think this is unlike most CS programs, and I'm so grateful for that experience. Computer science and programming was like a roller coaster for me. I loved it. But I also loved art, and didn’t want to give that up. 

The first time I heard of the words “Front-End Development” was at a [Refresh DC](http://refresh-dc.org/) meetup where [Dave Desandro](https://www.youtube.com/watch?v=n6FKT-KafRk) was speaking. He was talking about how he built a storybook using CSS 3D transforms and I remember having the thought: **"HOLY SHIT. THERE’S A NAME FOR IT!”** It was the perfect marriage of art and math.

At the following Refresh DC, I learned about Sass and Compass from Trevor Davis. After seeing him speak, I asked about what it took to become an intern for the company he worked at, [Viget](http://viget.com/), a year before I could qualify (I was too young). I got a list of suggested books and studied, studied, studied until I got the internship the following year. I fell in LOVE with front-end development. I remember staying in the office until midnight some nights (because I had a thunderbolt monitor to do Treehouse tutorials on!) and I’d get lectured by Trevor the next day for working too much (sorry). Viget was an amazing experience :smile: 

I ended up doing a CS minor instead of major because the classes didn’t align with my new-found perspective and interests (we offered very back-end-focused classes like cryptography when I wanted to learn front-end development, which wasn't a thing in academia at the time) so I took internships (SO MANY INTERNSHIPS) and learned a bit of PHP, JS, semantic HTML, working with databases, and Sass. (Though my absolute favorite course in university was Discrete Structures for Computer Science :heart: :smile:  )

I’ve had some great experiences, but I’ve also had some pretty terrible ones. Like most women in this industry, I've worked in more than one shockingly sexist environment. I was harassed out of my first company at age 20 by a nearly 30-year-old man, and when I told the CEO he said “I’m sorry that happened to you." I get shit **all** the time for not being a “real” developer because I am decent at drawing and designing things, even though I code all day at work, at home, and mentor a lot of people in development. Yes, the tech industry is in a shitty situation and it needs to get better, and yes, I am usually (9 times out of 10) The Only Girl™ in the room, but my absolute love for the medium overpowers that.

I grew up without restrictions on my access to technology, and for that I am grateful. It was only when I started working in the field that I saw the how detrimental this monoculture is in a work environment. I’m no longer trying to be “one of the guys” to fit in. Since after all, **I became a developer because I liked drawing dresses out of pixels.**

**Comment by diessica** [comment]
Your childhood's stories are  just beautiful, and you are definitely a Neopets hacker. I'm sure that the bad things that happened only made you become better at Neopets hacking.

Very inspiring story about hard work, but also about love and simplicity.

Thank you for sharing!

**Comment by notenociz** [comment]
Is this going to be published on Medium or something?

**Comment by una** [comment]
I wasn't planning on it originally -- should it be @enociz?

**Comment by diessica** [comment]
I think it is way too personal. It could easily be an [awesome-ama-answer](https://github.com/stoeffel/awesome-ama-answers), though! :D

**Comment by notenociz** [comment]
It really matters on your thoughts @una. Like @diessica said, it's a bit personal but I definitely think that there is a moral in it (working hard, overcoming stereotypes). Whether you do or don't, I commend you on sharing and found it a real insight into just how diverse (not much) and nurturing (pretty good) our community is especially since not everyone shares how they were helped and male like myself need things like this to show us just how we can help our community. +1
