### ISSUE TITLE
So why is :wq sticker-worthy?

### ISSUE THREAD

**Issue by AmeliaBR** [una/ama#22]
(For those of us who are actually interested in your perspective on text editing environments and shortcut commands thereof.)

**Comment by una** [comment]
Firstly, my laptop is _covered_ in stickers (see image), so it was just one of many for this person to pick out:

![img_9224](https://cloud.githubusercontent.com/assets/1693164/9215920/f356f310-4076-11e5-92e0-29c84e834502.JPG)

I love the `:wq` sticker because I got it at a time that I was really focused on learning/using Vim and terminal/writing aliases and minor shell script things to improve my workflow :smile:  My friend Ian gave it to me and I love it. I mostly use Sublime because it has a lot of really nice features that I love and I have a really great [setup](https://github.com/una/dotfiles) but I use Vim for a few edits and bug fixes since its so quick and easy to access in my terminal. I didn't think it would become a big deal at al.

**Comment by AmeliaBR** [comment]
That is the nerdiest-fabulous collection of stickers ever. Thanks for sharing!
