### ISSUE TITLE
How do you balance time for learning new tech vs. your day job?

### ISSUE THREAD

**Issue by markpalfreeman** [una/ama#26]
To help frame the question:
- When do you get time to learn new things?
- How much of your "free time" is devoted to learning code?
- Do you have to make a lot of sacrifices in your "personal life" to stay up things?

**Comment by una** [comment]
Wow this is a great question. I like that you asked "how do you balance time" and not "how do you find time," which is how this question is normally phrased, and after an eyeroll I always respond: "you don't _find_ time -- you **make** time"

And making time is hard. But worth it.

I make time in between all the little things. Thats why I _listen_ to blog posts, podcasts, and audiobooks instead of _read_ blogs. It takes less time and I can multitask (THANK YOU [POCKET](http://getpocket.com) TTS). I wake up, turn on a podcast, and do my makeup while learning about GSAP (that's what I did this morning). I make lists of things I know I want to get done and make sure to focus on individual tasks. Lists are key. I need to write out smaller tasks and such that I want to accomplish to make sure I remember to make time for them.

To be perfectly honest, _most_ of my free time is devoted to something tech-related, whether it be making slides for a presentation, or learning new tech/code/stylistic things, or writing a blog post, or listening to podcasts.

But it is really hard to stay up on things as well as maintain a personal life. I try to balance both by siloing activities. If i'm going out with my friends -- I am fully immersed in that. If I am focusing on finishing a presentation, I turn off my phone and block Twitter/Facebook with the [Self Control](https://selfcontrolapp.com/) app. The more focused I can get, the more I can sleep at night and still feel accomplished :zzz: 

Somehow my work has become my life and visa versa so I might not be the best person to ask about work/life balance, but I really love what I do. I find it challenging and exciting to learn new things, so I don't mind it for now. I'm happy and that's balance enough for me :sweat_smile:
