### ISSUE TITLE
How do you get emojis into your URLs?

### ISSUE THREAD

**Issue by huijing** [una/ama#27]
I frequent your blog and one thing I love is the emojis in the URL. Reminded me of Glen Chiacchieri's URL animations some how. :p

**Comment by una** [comment]
:D It's actually a super-easy url trick:

```
  function addEmoji() {
    if (navigator.userAgent.indexOf('Mac OS X') != -1) {
      window.location.hash = "💁";
    }
  };
  addEmoji();
```

All I am doing is adding the emoji after a hash. I'm checking for Mac users because the emoji was causing some non-Mac users URLs to break and not be able to access my site. I'm also adding it as a hash because if it were part of the URL "proper," going to any link without the emoji would 404. But adding an emoji hash is harmless otherwise on Mac :smile:
