### ISSUE TITLE
How did you come up with the ideas for the "Photoshop Is Dead!" talk?

### ISSUE THREAD

**Issue by khalillechelt** [una/ama#33]
I really enjoyed [your talk at CSSconf](https://www.youtube.com/watch?v=LY65F2e4B5w) this year. I was wondering how did you come up with your idea? How did it start out and how did you get it developed into what it was?
How much do you actually use the Browser instead of Photoshop?

Do you use this method of designing at work? Are people confused by it?

**Comment by una** [comment]
I do a _lot_ of designing in the browser. In fact, the entire website I shared (http://travels.surge.sh) was designed solely in the browser. 

The talk idea came out of the realization that I don't actually use Photoshop anymore because of CSS, and I wanted to open people's eyes to what was out there. It was pushed forward by frustration while waiting for Photoshop to open and the final straw was an inability to even open Photoshop because of CC Account issues and wifi.

The original outline didn't focus only on image effects -- that was just 1/5 topics I wanted to cover, but as I did more research and played around with effects, I scoped it down. So look out for some new talk topics next year on the rest :smile:
