### ISSUE TITLE
How did you loose 15lbs?

### ISSUE THREAD

**Issue by mxstbr** [una/ama#44]
🎉 Congratulations! What did you do differently, and how much more weight do you want to lose?

**Comment by una** [comment]
Thanks! I'm probably about half way there to #goals :) But I'm pretty happy with the changes.

Basically, the biggest change is that I got a break from traveling for tech conferences/events! Which meant that I could actually go to the gym regularly and have full control over my diet. I started tracking on MyFitnessPal and am a big fan of the Ketogenic or Paleo diet (I've have a lot of sucess on Paleo in the past, but believe in the science behind Keto). Basically, I do a mix -- so I have a high protein, med fat, low carb diet around 1200 calories a day. I also started drinking less (and when I do drink, I get wine), going to the gym more, and replacing a meal every day with a 140 calorie, 2g carb, 20g protein shake.

Here's the protein shake I love :smile::
- 1 scoop Jay Robb Vanilla Whey Protein
- Unsweetened Vanilla Almond Milk (probably about 3/4 of a cup)
- Cinnamon
- a little bit of Sea Salt (it really brings out the flavor)
- Ice
- Instant Coffee (optional)

I usually have it for breakfast -- but sometimes I'll make an egg white omelet for breakfast and have it for dinner instead.

As far as working out goes, I bike or walk everywhere on the weekend instead of drive. At the gym, I do a bit of weight lifting and crossfit-like things such as throwing those weighted sandbag-filled balls against the wall (wall balls) and doing squats in between. When I do sets, I do "super-sets" AKA 2-3 moves and take a break in between. Jump roping in between weight-lifting (tabata style) is also really effective :key: 

Anyway, that's just what works for me :) I still go out with friends, I just make sure to get my work out in and avoid heavy carbs.

**Comment by mxstbr** [comment]
Wow that was an in-depth answer, thank you! I'm not convinced of the sea salt, though the rest sounds delicious – much better than the regular "Mix peanut butter with bananas and lots of protein powder" shakes.

A short follow-up: How hard has it been to stick to your diet and how much (more) time do you invest in your food?

**Comment by una** [comment]
I invest a lot _less_ time into my food -- it's quick and easy. I hardly cook anymore other than chicken breast because I eat a lot of salads (though I am thinking of starting that meal-prep-Sunday sort of thing).  And when I'm out I always look for the healthiest option so, decisions are easy

**Comment by mxstbr** [comment]
Interesting, thanks for the answers! :+1:

**Comment by spences10** [comment]
How's the gym going now with all the travelling @una?

I lost 22 lbs with fasting via the 5:2 diet, basically just cut your overall cals then I got more into the [lean gains] 16/8 managed to lose an additional 11 lbs, don't worry I've since been ill over Christmas last year and gained it all back :upside_down_face: I'm back at the gym three days a week now :weight_lifting_man: 

16/8 is basically fast for 16 hrs and have your allotted calories for that day in the remaining 8, you cycle carbs and fats, so workout days high carbs for dat dere glycogen and rest days high fats for hormone balance and the good feels, every day is high protein :+1: 

I own a nutri bullet which is great for making teh shakes, my fav at the moment:

* Porridge 65 g
* Frozen fruit 200 g
* 1% Choco Milk 500 ml
* 1 free range egg
* 50 g choco whey
* rest of the container filled with spinach/kale

:heart_eyes:
