### ISSUE TITLE
Advice for new front-end developers?

### ISSUE THREAD

**Issue by markpalfreeman** [una/ama#8]
Hey @una,
What type of advice would you give to newer devs entering the front-end space today?

Ex: importance of Javascript, UI, "computer programming" skills, plugging into community, etc.

**Comment by una** [comment]
Just because you're learning, it doesn't mean you can't teach! Keep a blog, document what you're doing, and share your knowledge. Teaching is a great way to solidify concepts.

Re: the practical things -- get the basics down. Understand vanilla JS, CSS, and semantic HTML. Understanding the structure and underlying concepts goes a long way!
