### ISSUE TITLE
Something you're mistakenly thought to be naturally good at?

### ISSUE THREAD

**Issue by burin** [una/ama#9]
What's something you're really good at that people think you're just naturally good at, when in reality you spent a lot of effort getting better at over time?

e.g. drinking orange juice right after brushing your teeth with a straight face, or putting two socks on at the same time

**Comment by una** [comment]
Probably development -- I work REALLY hard at Javascript, and I'm not great at it, but I try and spend a LOT of my free time working at it.

Also people used to assume I was good at basketball growing up because I was tall for my age. But I suck at basketball. There's no getting around that :stuck_out_tongue_closed_eyes:
